version: "3.3"
services:
  screeps-server:
    build:
      context: ./screeps-server
      dockerfile: Dockerfile
      args:
        screeps_version: 3.4.3
        node_version: node:8-alpine
    image: ika108/screeps-server:latest
    command: run
    container_name: screeps-server
    ports:
      - 21025:21025
      - 21026:21026
    hostname: server-screeps
    volumes:
      - screeps_data:/screeps
    restart: on-failure
    env_file:
     - .env
volumes:
  screeps_data:
